services:
  mybangs:
    image: git.1horn.dev/kilian/mybangs:latest
    ports:
      - 8000:8000
    environment:
      - SECRET="" #generate with openssl rand -hex 16
      - HOST="" # for example mybangs.party
      - DEFAULT_BANGS="" # something like {"Default": "https://www.google.com/search?q=%s", "gh": "https://github.com/search?q=%s"}
      - CUSTOM_FOOTER="" # html code displayed in the footer
